#!/bin/bash

# This is a launcher (main menu) for all scripts
# that manage the media center files.
# Tarso Galvao 05/04/23 Debian 11


## load enviroment variables
if [ -f $HOME/bmm/.env ]; then
    . $HOME/bmm/.env
else
	echo 'BASH MEDIA MANAGER'
	echo 'No enviromento found! Entering setup...' && sleep 2;
    clear && eval $HOME/bmm/bmm-setup_enviroment;
    exit 0;
fi

## Main Menu
menu_opt=$(dialog --colors --no-cancel --no-lines\
	--title 'Script-Launcher Menu' \
	--backtitle "\Z7Bash Media Manager" \
	--stdout \
	--menu '								Up and down arrows change selection.\n											Use the Enter key to confirm.' \
	0 0 0 \
	'converter_mp3' 'Converts Audio files to MP3' \
	'converter_mp4' 'Converts Video files to MP4' \
	'dir_cleaner' 'Removes Empty Audio Folders' \
	'media_backup' 'Media Backup Manager' \
	'media_permissions' 'Fix Media Permissions' \
	'media_share' 'Easily Share Media' \
	'setup_enviroment' 'Setup Enviroment Variables' \
	'quit' 'Quit to shell');

# Exit on Quit or Cancel || Execute chosen script.
if [ $menu_opt = 'quit' ] || [ $? -ne 1 ]; then
	clear && exit 0
else
	clear && eval bmm-$menu_opt
	exit 0;
fi
