#!/bin/bash

## Fix/modify permissions of media files to work
## with arr* software or use manual custom entries.
## Uses 2775 for folders and 664 for files as standard.
## Tarso Galvao 08/04/23 Debian 11 (Based on Snortt's script)

## load enviroment variables
if [ -f $HOME/bmm/.env ]; then
    . $HOME/bmm/.env
else
    echo -e "FATAL ERROR: .env not found.$\n
	Use bmm-setup_enviroment to create one.\nAborting...";
    exit 1;
fi

## DO STUFF ($1-path $2-user $3-group)
fix_permissions () {
	for _dir in $1
	do
		echo "Processing $4..."
		echo -e "Path: $1"
		sudo chown -R $2:$3 ${_dir} && echo -e "${WARN}Ownership: ${OK}OK${NC}"
		sudo find ${_dir} -type d -exec chmod 2775 {} \; && echo -e "${WARN}Folders: ${OK}OK${NC}"
		sudo find ${_dir} -type f -exec chmod 664 {} \; && echo -e "${WARN}Files: ${OK}OK${NC}"
	done
}

## user input entries (Custom)
custom_entry () {
	## get path
	path=$(dialog --no-lines --colors \
		--backtitle "\Z7Bash Media Manager" \
		--title "Media Permissions" \
		--inputbox "Enter full path: \n \
		( ex.: /full/path/to/dir/ )" 10 40 \
		3>&1 1>&2 2>&3 3>&-)
	clear #check path:
	if [ "$path" == "" ]; then echo -e "${ERROR}No path, aborting...${NC}"; sleep 2;
		clear && eval bmm-launcher; exit 1; fi
	## get user
	user=$(dialog --no-lines --colors \
		--backtitle "\Z7Bash Media Manager" \
		--title "Media Permissions" \
		--inputbox "Enter user: \n \
		( ex.: dietpi or 1000 )" 10 40 \
		3>&1 1>&2 2>&3 3>&-)
	clear #check user:
	if [ "$user" == "" ]; then echo -e "${ERROR}No user, aborting...${NC}"; sleep 2;
		clear && eval bmm-launcher; exit 1; fi
	## get group
	group=$(dialog --no-lines --colors \
		--backtitle "\Z7Bash Media Manager" \
		--title "Media Permissions" \
		--inputbox "Enter group: \n \
		( ex.: dietpi or 1000 )" 10 40 \
		3>&1 1>&2 2>&3 3>&-)
	clear #check group:
	if [ "$group" == "" ]; then echo -e "${ERROR}No group, aborting...${NC}"; sleep 2;
		clear && eval bmm-launcher; exit 1; fi
	## execute with user input args
	fix_permissions $path $user $group "CUSTOM PATH"
}

main_menu () {
	checklist=(dialog --no-lines --colors \
		--backtitle "\Z7Bash Media Manager" \
		--separate-output --checklist "Select a preset: (use spacebar)" 22 76 16)
	options=(1 "Audio $AUDIO_OWNER:$GROUP" off    
			2 "Series $SERIES_OWNER:$GROUP" off
			3 "Movies $MOVIES_OWNER:$GROUP" off
			4 "Concerts $CONCERTS_OWNER:$GROUP" off
			5 "Stand-up $STANDUP_OWNER:$GROUP" off
			6 "Custom" off)
	choices=$("${checklist[@]}" "${options[@]}" 2>&1 >/dev/tty)
	clear
	for choice in $choices
	do
		case $choice in
			1)
				fix_permissions $AUDIOROOT $AUDIO_OWNER $GROUP "AUDIO"
				;;
			2)
				fix_permissions $SERIESROOT $SERIES_OWNER $GROUP "SERIES"
				;;
			3)
				fix_permissions $MOVIESROOT $MOVIES_OWNER $GROUP "MOVIES"
				;;
			4)
				fix_permissions $CONCERTSROOT $CONCERTS_OWNER $GROUP "CONCERTS"
				;;
			5)
				fix_permissions $STANDUPROOT $STANDUP_OWNER $GROUP "STAND-UP"
				;;
			6)
				custom_entry
				;;
		esac
	done
	## go back to launcher if nothins is selected
	clear && eval bmm-launcher; exit 1;
}

## STATUP OPTIONS
if [ "$1" = '-a' ] || [ "$1" = '--audio' ]; then
	fix_permissions $AUDIOROOT $AUDIO_OWNER $GROUP "AUDIO"

elif [ "$1" = '-s' ] || [ "$1" = '--series' ]; then
	fix_permissions $SERIESROOT $SERIES_OWNER $GROUP "SERIES"

elif [ "$1" = '-m' ] || [ "$1" = '--movies' ]; then
	fix_permissions $MOVIESROOT $MOVIES_OWNER $GROUP "MOVIES"

elif [ "$1" = '-c' ] || [ "$1" = '--concerts' ]; then
	fix_permissions $CONCERTSROOT $CONCERTS_OWNER $GROUP "CONCERTS"

elif [ "$1" = '-u' ] || [ "$1" = '--stand-up' ]; then
	fix_permissions $STANDUPROOT $STANDUP_OWNER $GROUP "STAND-UP"

elif [ "$1" = '-t' ] || [ "$1" = '--target' ]; then
	fix_permissions $2 $3 $4 "CUSTOM PATH"

elif [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
	if ! command -v $BANNER >> /dev/null; then echo -e "${WARN}BASH MEDIA MANAGER${NC}"; else eval $BANNER; fi
	echo -e "${OK}Media Permissions${NC}"
	echo -e "Fix file/folder permissons for media software."
	echo -e "Use with no arguements to enter the GUI."
	echo -e "${WARN}Folders: Folders, owners and group are set up in .evn file.${NC}"
	echo -e "USAGE: bmm-media_permissions [-arg] [--arg]\n"
	echo -e " -a [--audio]		 -> Fix all audio permissions"
	echo -e " -s [--series]		 -> Fix all series permissions"
	echo -e " -m [--movies]		 -> Fix all movies permissions"
	echo -e " -c [--concerts]	 -> Fix all concerts permissions"
	echo -e " -u [--stand-up]	 -> Fix all stand-up permissions"
	echo -e "${WARN} -s [--target]		 -> Manually enter desired settings."
	echo -e " Usage: bmm-media_permissions [-t] [--target] /dir/path user group${NC}"
	echo -e " -h [--help]		 -> Shows this screen."
else
	main_menu;
fi
