#!/bin/bash
# 
# Logs unauthorized logins attempts, based on records from /var/log/auth.log
# 
# Gabriel Marques 
# snortt@gmail.com
#
# Sep 2018 

MAIL_TITLE="[Audit::SSH Logins]"
MAIL_RCPT="tarsogalvao@gmail.com"
AUTHFILE="/var/log/auth.log"
OUTFILE="/home/dietpi/SSH_Attempts.txt"

help() {
    echo "Usage ${0%/*} [--help|--show-jails|--send-mail]"
    echo "--show-jails  --> Print jails details"
    echo "--send-mail   --> Sends report by mail ($MAIL_RCPT)"
    exit 202
}

if [ "$1" == "--help" ]; then
    help
fi

me=$(id -u)

if [ "$me" -ne "0" ]; then
	echo -e "I need to be root"
	exit 201
fi

show_jails=0
send_mail=0
pc_mode="0"

for arg in $@
do
    if [ "$arg" == "--help" ] || [ "$arg" == "-h" ]; then
        help
    fi 

    if [ "$arg" == "--show-jails" ]; then
        echo "Showing jails details"
        show_jails=1
    fi
    
    if [ "$arg" == "--send-mail" ]; then
        echo "Report will be sent by mail"
        send_mail=1
    fi
done 

echo -e "--------------------" > ${OUTFILE}
date >> ${OUTFILE} 
echo -e "" >> ${OUTFILE}
echo -e "These are the logins registered until $(date), as found in ${AUTHFILE}" >> ${OUTFILE}
echo -e "---------------------" >> ${OUTFILE}
# We need to generate auth.log from SSH unit's Journal
journalctl -u ssh --no-pager > $AUTHFILE 
total="0"
IFS="\n
"
#for entry in $(grep 'Failed password' ${AUTHFILE} | awk -F " " '{print $1 " " $2 " " $3 ", user:" $9 ", ip:" $11 }')
for entry in $(grep -Ei 'from.*port.*ssh' ${AUTHFILE} | grep -Evi 'disconnect|banner' | awk -F " " '{print $1 " " $2 " " $3 ", user:" $9 ", ip:" $11 }')
do
    ((total=total+1))
    echo "${total}: $entry" >> ${OUTFILE}
done
echo "Total logins: $total" | tee -a ${OUTFILE}

echo -e "" >> ${OUTFILE}

if [ "$show_jails" -eq "0" ]; then
    echo -e "You can check the banned IPs list with fail2ban-client status ssh sshd" >> ${OUTFILE}
else
    echo "----------" >> ${OUTFILE}
    echo "Banned IPs" >> ${OUTFILE}
    for jail in sshd 
    do
        fail2ban-client status $jail >> ${OUTFILE}
    done
fi

echo "Report saved in ${OUTFILE}"
if [ "$send_mail" -eq "1" ]; then
    cat $OUTFILE | mail -s "$MAIL_TITLE" ${MAIL_RCPT}
    echo "e-Mail sent to ${MAIL_RCPT}"
fi
