#!/bin/bash

## load enviroment variables
if [ -f $HOME/bmm/.env ]; then
    . $HOME/bmm/.env
else
    echo -e "FATAL ERROR: .env not found.$\n
	Use surserver-setup_enviroment to create one.\nAborting...";
    exit 1;
fi

PRESETS=("Very Fast 1080p30" "Very Fast 720p30" "Very Fast 480p30")
FORMATS=("mp4" "avi" "mkv" "rm")


##temp for test
PRESET="Very Fast 720p30"
FORMAT="avi"

execute_tasks () {
    dep_check handbrake-cli;

    while IFS= read -d '' -r ITEM
    do
        echo -e "Target: ${OK}$ITEM${NC}"  # full path of item.

        ## MOVE ORIGINAL to junk
        FILE=${ITEM##*/}  # individual file name.
        echo "Moving original file: $FILE"
        mv "$ITEM" "$VIDEOSJUNK"

        ## SET SOURCE
        SOURCE="$VIDEOSJUNK$FILE"
        echo -e "Processing source: ${WARN}$SOURCE${NC}"

        ## SET DEST
        EXT=${ITEM##*.}  # get file extension
        EXT=$(echo $EXT | tr "[:upper:]" "[:lower:]")  # normalize extension
        TARGET="${ITEM%.*}.$EXT" # normalize target destination ext
        DEST="${TARGET/."${FORMAT}"}.mp4" #set destination path.ext
        echo -e "Destination: ${WARN}$DEST${NC}"

        ## DO STUFF
        eval $(echo -e "handbrake-cli -i \"$SOURCE\" -o \"$DEST\" --preset \"$PRESET\" --optimize")

    done< <(find "$MEDIAROOT" -iname "*.$FORMAT" -print0)
}

if [ "$1" == '-t' ] || [ "$1" == '--target' ]; then
    MEDIAROOT=$2
    FORMAT=$3
    PRESET=$4
    execute_tasks;

elif [ "$1" == '-p' ] || [ "$1" == '--presets' ]; then
    for preset in "${PRESETS[@]}"
    do
        ((i++))
        echo -e "Preset $i: ${OK}\"$preset\"${NC}"
    done

elif [ "$1" == '-h' ] || [ "$1" == '--help' ]; then
    if ! command -v $BANNER >> /dev/null; then echo -e "${WARN}BASH MEDIA MANAGER${NC}"; else eval $BANNER; fi
    echo -e "Converter MP4"
    echo -e "Converts VIDEO files to \"H.264 AAC-2.0 Web-Optimized .mp4\" for streaming"
    echo -e "Usage: surserver-converter_mp4 [-arg] [--arg] [args]\n"
    echo -e " -p [--presets]    -> List available presets"
    echo -e " -t [--target]     -> Convert 'format' files from 'target folder' using \"preset\"."
    echo -e "                   Usage: surserver-converter_mp4 --target \"/path/to/dir/\" \"format\" \"preset\""
    echo -e "                   Ex: surserver-converter_mp4 --target \"/mnt/videos/\" \"avi\" \"Very Fast 720p30\""
    echo -e " -h [--help]       -> Shows this screen."
else
    echo 'menu will be called here'
fi