#!/bin/bash

## load enviroment variables
if [ -f $HOME/bmm/.env ]; then
    . $HOME/bmm/.env
else
    echo -e "FATAL ERROR: .env not found.$\n
	Use surserver-setup_enviroment to create one.\nAborting...";
    exit 1;
fi

PRESETS=("Very Fast 1080p30" "Very Fast 720p30" "Very Fast 480p30")
FORMATS=("mp4" "avi" "mkv" "rm")
dep_check handbrake-cli;

## $ surserver-converter_mp4 /mediarootfolder
MEDIAROOT=$1

##temp for test
PRESET="Very Fast 720p30"
FORMAT="avi"

while IFS= read -d '' -r ITEM
do
    echo -e "Target: ${OK}$ITEM${NC}"  # full path of item.

    ## MOVE ORIGINAL to junk
    FILE=${ITEM##*/}  # individual file name.
    echo "Moving file to junk: $FILE"
    mv "$ITEM" "$VIDEOSJUNK"

    ## SET SOURCE
    SOURCE="$VIDEOSJUNK$FILE"
    echo -e "Processing source: ${WARN}$SOURCE${NC}"

    ## SET DEST
    EXT=${ITEM##*.}  # get file extension
    EXT=$(echo $EXT | tr "[:upper:]" "[:lower:]")  # normalize extension
    TARGET="${ITEM%.*}.$EXT" # normalize target destination ext
    DEST="${TARGET/."${FORMAT}"}.mp4" #set destination path.ext
    echo -e "Destination: ${WARN}$DEST${NC}"

    ## DO STUFF
    echo "" | handbrake-cli -i "$SOURCE" -o "$DEST" --preset "$PRESET" --optimize

done< <(find "$MEDIAROOT" -iname "*.$FORMAT" -print0)
