#!/bin/bash

## load enviroment variables
if [ -f $HOME/bmm/.env ]; then
    . $HOME/bmm/.env
else
    echo -e "FATAL ERROR: .env not found.$\n
	Use surserver-setup_enviroment to create one.\nAborting...";
    exit 1;
fi

PRESETS=("Very Fast 1080p30" "Very Fast 720p30" "Very Fast 480p30")
FORMATS=("mp4" "avi" "mkv" "rm")
dep_check handbrake-cli;

## $ surserver-converter_mp4 /mediarootfolder
MEDIAROOT=$1

##temp for test
PRESET="Very Fast 720p30"
FORMAT="avi"

while IFS= read -d '' -r ITEM
do
    echo "Target: $ITEM"  # full path of item.

    FILE=${ITEM##*/}  # individual file name.
    echo "Moving file to junk: $FILE"
    echo -e "mv "$ITEM" "$VIDEOSJUNK""

    SOURCE="$VIDEOSJUNK$FILE"
    echo "Processing source: $SOURCE"

    EXT=${ITEM##*.}  # get file extension
    EXT=$(echo $EXT | tr "[:upper:]" "[:lower:]")  # normalize extension
    TARGET="${ITEM%.*}.$EXT" # normalize target destination
    DEST="${TARGET/."${FORMAT}"}.mp4" #set destination
    echo "Destination: $DEST"

    echo -e "handbrake-cli -i "$SOURCE" -o "$DEST" --preset "$PRESET" --optimize"
    #   echo "" | handbrake-cli -i "$SOURCE" -o "$DEST" --preset "$PRESET" --optimize
    echo '---------------------'

done< <(find "$MEDIAROOT" -iname "*.$FORMAT" -print0)
