#!/bin/bash

## create new .env file or update(change) enviroment variables in .env file

# this script should be able to generate a new .env file in case one is not found
# it should also be able to edit an existing .env file with new settings easily
# should be noob-proof.


ENV_FILE='/home/dietpi/bin/.env_test'
KEYS=(AUDIOROOT AUDIOBACKUP AUDIOJUNK VIDEOSROOT VIDEOSBACKUP VIDEOSJUNK SERIESROOT \
       SERIESBACKUP MOVIESROOT MOVIESBACKUP CONCERTSROOT CONCERTSBACKUP AUDIO_OWNER \
       SERIES_OWNER MOVIES_OWNER CONCERTS_OWNER GROUP)

## check for env
if [ -f $ENV_FILE ]; then . $ENV_FILE; fi

#folders setup, user/groups setup
main_form () {
    # open fd
    exec 3>&1
    # Store fields to $filled_form variable
    filled_form=$(dialog --ok-label "Update" \
        --title "SurServer Setup Enviroment" \
        --form "        Fill in all fields or some features will not work.\n
            Make sure path start and end with '/'." \
        25 80 0 \
        "Audio root folder:" 1 2	"$AUDIOROOT" 	1 27 46 0 \
        "Audio backup folder:"    2 2	"$AUDIOBACKUP"  	2 27 46 0 \
        "Audio junk folder:"    3 2	"$AUDIOJUNK"  	3 27 46 0 \
        "Videos root folder:" 4 2	"$VIDEOSROOT" 	4 27 46 0 \
        "Videos backup folder:"    5 2	"$VIDEOSBACKUP"  	5 27 46 0 \
        "Videos junk folder:"    6 2	"$VIDEOSJUNK"  	6 27 46 0 \
        "Series root folder:" 7 2	"$SERIESROOT" 	7 27 46 0 \
        "Series backup folder:"    8 2	"$SERIESBACKUP"  	8 27 46 0 \
        "Movies root folder:" 9 2	"$MOVIESROOT" 	9 27 46 0 \
        "Movies backup folder:"    10 2	"$MOVIESBACKUP"  	10 27 46 0 \
        "Concerts root folder:" 11 2	"$CONCERTSROOT" 	11 27 46 0 \
        "Concerts backup folder:"    12 2	"$CONCERTSBACKUP"  	12 27 46 0 \
        "User owner of audios:"    13 2	"$AUDIO_OWNER"  	13 27 46 0 \
        "User owner of series:"    14 2	"$SERIES_OWNER"  	14 27 46 0 \
        "User owner of movies:"    15 2	"$MOVIES_OWNER"  	15 27 46 0 \
        "User owner of concerts:"    16 2	"$CONCERTS_OWNER"  	16 27 46 0 \
        "Group owner of media:"    17 2	"$GROUP"  	17 27 46 0 \
        2>&1 1>&3)
    # close fd
    exec 3>&-
    ## FIX ME: 1st (filled) line gets removed if we press CANCEL (or esc)
    ## TODO: check for / on start/end of folder fields...
    i=0
    while read -r line; do
        sed -i -e '/'"${KEYS[((i++))]}"'=/ s|=.*|='"\"${line}\""'|' $ENV_FILE
    done <<< "${filled_form}"
}

#auto:
#bash colors
#add original functions

if [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    echo -e "${OK}SurServer Setup Enviroment${NC}"
    echo -e "Create new .env file or update enviroment variables in .env file"
    echo -e "Usage: surserver-setup_enviroment [-arg] [--arg]\n"
    echo -e " -h [--help]      -> Shows this screen."
else
    main_form;
fi